# This file was generated by GoReleaser. DO NOT EDIT.
cask "schriftsatz" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "4f22557e58c0ce4ac53ae528fd4f5d8da19e9c9964df29e56be1e763a752f97b"
      url "https://github.com/cronai-labs/schriftsatz/releases/download/v#{version}/schriftsatz_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7a018ffc0b33767196343375334550bdb5f6867de83fbd79ba0a8375a89071f5"
      url "https://github.com/cronai-labs/schriftsatz/releases/download/v#{version}/schriftsatz_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9da3966811133c1992b1327b58f1712ac0a40fd90b2300a5654c397e4f7f22d1"
      url "https://github.com/cronai-labs/schriftsatz/releases/download/v#{version}/schriftsatz_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3cd9817455998117bdcb8a3f185c5ee454e5616945db45b1caf73f2c061d7c01"
      url "https://github.com/cronai-labs/schriftsatz/releases/download/v#{version}/schriftsatz_#{version}_linux_arm64.tar.gz"
    end
  end

  name "schriftsatz"
  desc "Markdown to print-ready PDF via pandoc and XeLaTeX, with a text layer that survives extraction"
  homepage "https://github.com/cronai-labs/schriftsatz"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "pandoc",
      "poppler",
      "texlive",
    ]

  binary "schriftsatz"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/schriftsatz"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    schriftsatz drives pandoc and XeLaTeX; both are installed as dependencies.

    The binary carries its own Lua filters and LaTeX fragments:
      schriftsatz --list-assets
      schriftsatz --print-asset styles/text-layer.tex

    Install uv for the second-extractor cross-check in `schriftsatz verify`.
  EOS
end
