# This file was generated by GoReleaser. DO NOT EDIT.
cask "schriftsatz" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "c09230624c8a888a84d965a12c944e6537b4ebd2bc456f3b16f4ed93e4858d34"
      url "https://github.com/cronai-labs/schriftsatz/releases/download/v#{version}/schriftsatz_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e8be339c39b06be67b79c2e153e3854a905ac1141d8e9928b1ffaa6b9a78f4ce"
      url "https://github.com/cronai-labs/schriftsatz/releases/download/v#{version}/schriftsatz_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b65c2fd394f04adbea9bbfb7463f92aa6a5d181ac4379e70b65eef5bca95afb3"
      url "https://github.com/cronai-labs/schriftsatz/releases/download/v#{version}/schriftsatz_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1d0d00b4c28475f10fe4aecab5002f9863694f39c57c677a7d80bf81e59ca1c0"
      url "https://github.com/cronai-labs/schriftsatz/releases/download/v#{version}/schriftsatz_#{version}_linux_arm64.tar.gz"
    end
  end

  name "schriftsatz"
  desc "Markdown to print-ready PDF via pandoc and XeLaTeX, with a text layer that survives extraction"
  homepage "https://github.com/cronai-labs/schriftsatz"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "pandoc",
      "poppler",
      "texlive",
    ]

  binary "schriftsatz"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/schriftsatz"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    schriftsatz drives pandoc and XeLaTeX; both are installed as dependencies.

    The binary carries its own Lua filters and LaTeX fragments:
      schriftsatz --list-assets
      schriftsatz --print-asset styles/text-layer.tex

    Install uv for the second-extractor cross-check in `schriftsatz verify`.
  EOS
end
