# This file was generated by GoReleaser. DO NOT EDIT.
cask "schriftsatz" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "4654e8d7d137e0a1cc0e53808413c66c6f8f0cd0109576bde2dee7caaa1e49aa"
      url "https://github.com/cronai-labs/schriftsatz/releases/download/v#{version}/schriftsatz_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b67d6eb8bbc917d9f6764ae6d7caace1f933a18835e1a0b7f997f2302e45cf43"
      url "https://github.com/cronai-labs/schriftsatz/releases/download/v#{version}/schriftsatz_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8a923d6f0682822e1cc289fa12432167f411a95812f465713d7925e224518d9d"
      url "https://github.com/cronai-labs/schriftsatz/releases/download/v#{version}/schriftsatz_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3eb54de83418215084b10c1556f4092617ca2cf1732b713711080e32ec2b12f8"
      url "https://github.com/cronai-labs/schriftsatz/releases/download/v#{version}/schriftsatz_#{version}_linux_arm64.tar.gz"
    end
  end

  name "schriftsatz"
  desc "Markdown to print-ready PDF via pandoc and XeLaTeX, with a text layer that survives extraction"
  homepage "https://github.com/cronai-labs/schriftsatz"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "pandoc",
      "poppler",
      "texlive",
    ]

  binary "schriftsatz"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/schriftsatz"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    schriftsatz drives pandoc and XeLaTeX; both are installed as dependencies.

    The binary carries its own Lua filters and LaTeX fragments:
      schriftsatz --list-assets
      schriftsatz --print-asset styles/text-layer.tex

    Install uv for the second-extractor cross-check in `schriftsatz verify`.
  EOS
end
